version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - docker build -t app .
  post_build:
    commands:
      - REPO_URL=$(python -c "print('$REPOSITORY_URI'.split('/')[0])")
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REPO_URL
      - docker tag app:latest $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:latest